import {
  text,
  boolean,
  bigint,
  integer,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core"
import { stripeSchema } from "./enums"

export const charges = stripeSchema.table("charges", {
  id: text("id").primaryKey(),
  object: text("object"),
  paid: boolean("paid"),
  order: text("order"),
  amount: bigint("amount", { mode: "number" }),
  review: text("review"),
  source: jsonb("source"),
  status: text("status"),
  created: integer("created"),
  dispute: text("dispute"),
  invoice: text("invoice"),
  outcome: jsonb("outcome"),
  refunds: jsonb("refunds"),
  updated: integer("updated"),
  captured: boolean("captured"),
  currency: text("currency"),
  customer: text("customer"),
  livemode: boolean("livemode"),
  metadata: jsonb("metadata"),
  refunded: boolean("refunded"),
  shipping: jsonb("shipping"),
  application: text("application"),
  description: text("description"),
  destination: text("destination"),
  failureCode: text("failure_code"),
  onBehalfOf: text("on_behalf_of"),
  fraudDetails: jsonb("fraud_details"),
  receiptEmail: text("receipt_email"),
  paymentIntent: text("payment_intent"),
  receiptNumber: text("receipt_number"),
  transferGroup: text("transfer_group"),
  amountRefunded: bigint("amount_refunded", { mode: "number" }),
  applicationFee: text("application_fee"),
  failureMessage: text("failure_message"),
  sourceTransfer: text("source_transfer"),
  balanceTransaction: text("balance_transaction"),
  statementDescriptor: text("statement_descriptor"),
  paymentMethodDetails: jsonb("payment_method_details"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
})

