import {
  text,
  boolean,
  integer,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core"
import { stripeSchema } from "./enums"

export const checkoutSessions = stripeSchema.table("checkout_sessions", {
  id: text("id").primaryKey(),
  object: text("object"),
  adaptivePricing: jsonb("adaptive_pricing"),
  afterExpiration: jsonb("after_expiration"),
  allowPromotionCodes: boolean("allow_promotion_codes"),
  amountSubtotal: integer("amount_subtotal"),
  amountTotal: integer("amount_total"),
  automaticTax: jsonb("automatic_tax"),
  billingAddressCollection: text("billing_address_collection"),
  cancelUrl: text("cancel_url"),
  clientReferenceId: text("client_reference_id"),
  clientSecret: text("client_secret"),
  collectedInformation: jsonb("collected_information"),
  consent: jsonb("consent"),
  consentCollection: jsonb("consent_collection"),
  created: integer("created"),
  currency: text("currency"),
  currencyConversion: jsonb("currency_conversion"),
  customFields: jsonb("custom_fields"),
  customText: jsonb("custom_text"),
  customer: text("customer"),
  customerCreation: text("customer_creation"),
  customerDetails: jsonb("customer_details"),
  customerEmail: text("customer_email"),
  discounts: jsonb("discounts"),
  expiresAt: integer("expires_at"),
  invoice: text("invoice"),
  invoiceCreation: jsonb("invoice_creation"),
  livemode: boolean("livemode"),
  locale: text("locale"),
  metadata: jsonb("metadata"),
  mode: text("mode"),
  optionalItems: jsonb("optional_items"),
  paymentIntent: text("payment_intent"),
  paymentLink: text("payment_link"),
  paymentMethodCollection: text("payment_method_collection"),
  paymentMethodConfigurationDetails: jsonb("payment_method_configuration_details"),
  paymentMethodOptions: jsonb("payment_method_options"),
  paymentMethodTypes: jsonb("payment_method_types"),
  paymentStatus: text("payment_status"),
  permissions: jsonb("permissions"),
  phoneNumberCollection: jsonb("phone_number_collection"),
  presentmentDetails: jsonb("presentment_details"),
  recoveredFrom: text("recovered_from"),
  redirectOnCompletion: text("redirect_on_completion"),
  returnUrl: text("return_url"),
  savedPaymentMethodOptions: jsonb("saved_payment_method_options"),
  setupIntent: text("setup_intent"),
  shippingAddressCollection: jsonb("shipping_address_collection"),
  shippingCost: jsonb("shipping_cost"),
  shippingDetails: jsonb("shipping_details"),
  shippingOptions: jsonb("shipping_options"),
  status: text("status"),
  submitType: text("submit_type"),
  subscription: text("subscription"),
  successUrl: text("success_url"),
  taxIdCollection: jsonb("tax_id_collection"),
  totalDetails: jsonb("total_details"),
  uiMode: text("ui_mode"),
  url: text("url"),
  walletOptions: jsonb("wallet_options"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
})

