import {
  text,
  boolean,
  integer,
  bigint,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core"
import { stripeSchema, invoiceStatusEnum } from "./enums"
import { customers } from "./customers"
import { subscriptions } from "./subscriptions"

export const invoices = stripeSchema.table("invoices", {
  id: text("id").primaryKey(),
  object: text("object"),
  autoAdvance: boolean("auto_advance"),
  collectionMethod: text("collection_method"),
  currency: text("currency"),
  description: text("description"),
  hostedInvoiceUrl: text("hosted_invoice_url"),
  lines: jsonb("lines"),
  metadata: jsonb("metadata"),
  periodEnd: integer("period_end"),
  periodStart: integer("period_start"),
  status: invoiceStatusEnum("status"),
  total: bigint("total", { mode: "number" }),
  accountCountry: text("account_country"),
  accountName: text("account_name"),
  accountTaxIds: jsonb("account_tax_ids"),
  amountDue: bigint("amount_due", { mode: "number" }),
  amountPaid: bigint("amount_paid", { mode: "number" }),
  amountRemaining: bigint("amount_remaining", { mode: "number" }),
  applicationFeeAmount: bigint("application_fee_amount", { mode: "number" }),
  attemptCount: integer("attempt_count"),
  attempted: boolean("attempted"),
  billingReason: text("billing_reason"),
  created: integer("created"),
  customFields: jsonb("custom_fields"),
  customerAddress: jsonb("customer_address"),
  customerEmail: text("customer_email"),
  customerName: text("customer_name"),
  customerPhone: text("customer_phone"),
  customerShipping: jsonb("customer_shipping"),
  customerTaxExempt: text("customer_tax_exempt"),
  customerTaxIds: jsonb("customer_tax_ids"),
  defaultTaxRates: jsonb("default_tax_rates"),
  discount: jsonb("discount"),
  discounts: jsonb("discounts"),
  dueDate: integer("due_date"),
  endingBalance: integer("ending_balance"),
  footer: text("footer"),
  invoicePdf: text("invoice_pdf"),
  lastFinalizationError: jsonb("last_finalization_error"),
  livemode: boolean("livemode"),
  nextPaymentAttempt: integer("next_payment_attempt"),
  number: text("number"),
  paid: boolean("paid"),
  paymentSettings: jsonb("payment_settings"),
  postPaymentCreditNotesAmount: integer("post_payment_credit_notes_amount"),
  prePaymentCreditNotesAmount: integer("pre_payment_credit_notes_amount"),
  receiptNumber: text("receipt_number"),
  startingBalance: integer("starting_balance"),
  statementDescriptor: text("statement_descriptor"),
  statusTransitions: jsonb("status_transitions"),
  subtotal: integer("subtotal"),
  tax: integer("tax"),
  totalDiscountAmounts: jsonb("total_discount_amounts"),
  totalTaxAmounts: jsonb("total_tax_amounts"),
  transferData: jsonb("transfer_data"),
  webhooksDeliveredAt: integer("webhooks_delivered_at"),
  customer: text("customer").references(() => customers.id),
  subscription: text("subscription").references(() => subscriptions.id),
  paymentIntent: text("payment_intent"),
  defaultPaymentMethod: text("default_payment_method"),
  defaultSource: text("default_source"),
  onBehalfOf: text("on_behalf_of"),
  charge: text("charge"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
})

