import {
  text,
  boolean,
  integer,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core"
import { stripeSchema } from "./enums"

export const paymentIntents = stripeSchema.table("payment_intents", {
  id: text("id").primaryKey(),
  object: text("object"),
  amount: integer("amount"),
  amountCapturable: integer("amount_capturable"),
  amountDetails: jsonb("amount_details"),
  amountReceived: integer("amount_received"),
  application: text("application"),
  applicationFeeAmount: integer("application_fee_amount"),
  automaticPaymentMethods: text("automatic_payment_methods"),
  canceledAt: integer("canceled_at"),
  cancellationReason: text("cancellation_reason"),
  captureMethod: text("capture_method"),
  clientSecret: text("client_secret"),
  confirmationMethod: text("confirmation_method"),
  created: integer("created"),
  currency: text("currency"),
  customer: text("customer"),
  description: text("description"),
  invoice: text("invoice"),
  lastPaymentError: text("last_payment_error"),
  livemode: boolean("livemode"),
  metadata: jsonb("metadata"),
  nextAction: text("next_action"),
  onBehalfOf: text("on_behalf_of"),
  paymentMethod: text("payment_method"),
  paymentMethodOptions: jsonb("payment_method_options"),
  paymentMethodTypes: jsonb("payment_method_types"),
  processing: text("processing"),
  receiptEmail: text("receipt_email"),
  review: text("review"),
  setupFutureUsage: text("setup_future_usage"),
  shipping: jsonb("shipping"),
  statementDescriptor: text("statement_descriptor"),
  statementDescriptorSuffix: text("statement_descriptor_suffix"),
  status: text("status"),
  transferData: jsonb("transfer_data"),
  transferGroup: text("transfer_group"),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
})

